apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeder
  namespace: br1-health100
  labels:
    app: seeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeder
  template:
    metadata:
      labels:
        app: seeder
    spec:
      containers:
      - name: seeder
        image: ko://github.com/yolocs/ce-test-actor/cmd/seeder
        env:
        - name: TARGET
          value: http://broker-ingress.cloud-run-events.svc.cluster.local/br1-health100/testbroker
        - name: INTERVAL
          value: 5s
