apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeder
  namespace: default
  labels:
    app: seeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seeder
  template:
    metadata:
      labels:
        app: seeder
    spec:
      containers:
        - name: seeder
          image: ko://github.com/capri-xiyue/ce-test-actor/cmd/topic-seeder
          env:
            - name: INTERVAL
              value: "1s"
            - name: CONCURRENCY
              value: "10000"
            - name: TOPIC_ID
              value: "test-topic"