apiVersion: apps/v1
kind: Deployment
metadata:
  name: actor
  namespace: br4-echo10
  labels:
    app: actor
spec:
  replicas: 6
  selector:
    matchLabels:
      app: actor
  template:
    metadata:
      labels:
        app: actor
    spec:
      containers:
      - name: actor
        image: ko://github.com/yolocs/ce-test-actor/cmd/actor
        ports:
        - containerPort: 8080
        env:
        - name: ECHO_HOSTS
          value: "*"

